apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: cluster-external-secret-2
spec:
  # The name to be used on the ExternalSecrets
  externalSecretName: "external-secret-2"

  # This is a basic label selector to select the namespaces to deploy ExternalSecrets to.
  # you can read more about them here https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#resources-that-support-set-based-requirements
  namespaceSelector:
    matchLabels: 
      name: external-secrets

  # How often the ClusterExternalSecret should reconcile itself
  # This will decide how often to check and make sure that the ExternalSecrets exist in the matching namespaces
  refreshTime: "1m"

  # This is the spec of the ExternalSecrets to be created
  # The content of this was taken from our ExternalSecret example
  externalSecretSpec:
    refreshInterval: 1m
    secretStoreRef:
      name: external-secret-store-2
      kind: ClusterSecretStore
    target:
      name: wk-first-aws-secret-actual-2 # DEST - name of the k8s secret that will be mapped to
      creationPolicy: Owner
    data:
    - secretKey: wk-first-aws-secret # DEST - name of the key in the k8s secret that will be mapped to
      remoteRef:
        key: wk-first-aws-secret # SOURCE - name of the aws secret
        property: my-key # SOURCE - key of the key-value pair inside the aws secret