apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret
  namespace: external-secrets
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: secret-store-1
    kind: SecretStore
  target:
    name: wk-first-aws-secret-actual # DEST - name of the k8s secret that will be mapped to
    creationPolicy: Owner
  data:
  - secretKey: my-key # DEST - name of the key in the k8s secret that will be mapped to
    remoteRef:
      key: wk-first-aws-secret # SOURCE - name of the aws secret
      property: my-key # SOURCE - key of the key-value pair inside the aws secret