apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secret-store
  namespace: external-secrets
spec:
  provider:
    aws:
      auth:
        secretRef:
          accessKeyIDSecretRef:
            key: access-key
            name: aws-secret
          secretAccessKeySecretRef:
            key: secret-access-key
            name: aws-secret
      region: ap-southeast-1
      service: SecretsManager
  retrySettings:
    maxRetries: 3
    retryInterval: '10s'
  refreshInterval: 3600
