apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret
  namespace: external-secrets
spec:
  refreshInterval: 2h
  secretStoreRef:
    name: secret-store
    kind: SecretStore
  target:
    name: wk-secret-as-file # DEST - name of the k8s secret that will be mapped to
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # multiline string
        app.properties: |
          key1={{ .k1 }}
          key2={{ .k2 }}
  data:
  - secretKey: k1 # DEST - name of the key in the k8s secret that will be mapped to
    remoteRef:
      key: wk-first-aws-secret # SOURCE - name of the aws secret
      property: k1 # SOURCE - key of the key-value pair inside the aws secret
  - secretKey: k2 # DEST - name of the key in the k8s secret that will be mapped to
    remoteRef:
      key: wk-first-aws-secret # SOURCE - name of the aws secret
      property: k2 # SOURCE - key of the key-value pair inside the aws secret